### ISSUE TITLE
Unable to Build Solution Due to Nuget Package Errors

### ISSUE THREAD

**Issue by hismightiness** [cantarus/PolyDeploy#1]
This may not be an issue that's directly related to this solution.  Please feel free to close this if that's the case.

Steps to Reproduce:

1. Fork and clone the repo
2. Create a new branch from the Development branch
3. Open the solution in VS 2017
4. Build the solution in debug mode

Expected Behavior:
The solution builds successfully.

Actual Behavior:
The build process takes a long time the first time and fails with the errors in the link below.  Subsequent builds simply fail immediately.  It appears that the DNN Nuget packages are not available or the configuration needs to be updated to allow the packages to be included.

https://www.screencast.com/t/vwBfP4Iv

**Comment by hismightiness** [comment]
By the way, I have a potential pull request planned.  I can technically test without this working, but it would be nice to build just the same.  ;)

**Comment by hismightiness** [comment]
Actually, that's not true because there's no module package in your releases.  :(

**Comment by leeadams** [comment]
Thanks Will; we've just given you a shout-out on Twitter for being the first person to provide us with feedback on PolyDeploy! :) We're hoping to look at this tomorrow so please bear with us.

**Comment by can-anierzad** [comment]
Firstly, thank you for such a detailed and descriptive issue report. It's great when you can read an issue and know immediately what the problem is.

PolyDeploy uses a handful of NuGet packages which are hosted by our internal NuGet server. Of course, as this is internal, anyone outside our organisation is unable to access it and as a result Visual Studio will fail to restore those packages.

For the short term, modifying the following references to point at the appropriate DLLs in your development website's `bin` directory should allow the solution to build. Please don't commit these changes, though.
- `DotNetNuke`
- `DotNetNuke.Web`
- `DotNetNuke.Web.Client`
- `Newtonsoft.Json`

In the meantime, I'll see what can be done about this issue as it will affect everyone outside our organisation.

I've already taken a sneaky peek at the feature branch you've been working on and we're keen to have it. Thank you for taking the time to contribute.

**Comment by hismightiness** [comment]
http://www.dnnsoftware.com/community-blog/cid/154578/official-dotnetnuke-nuget-packages

https://www.nuget.org/packages/DotNetNuke.Bundle/

**Comment by hismightiness** [comment]
It's my pleasure to help!  :)

**Comment by can-anierzad** [comment]
I'm actually most of the way through swapping out our internal NuGet packages in favour of the official DNN packages. Unable to use the `DotNetNuke.Bundle` though unfortunately as it starts at 9.0.1.

The only DLL I have had to increase the version of beyond 7.0.0 is `DotNetNuke.Web.Client` as the earliest version available appears to be 7.4.2.

**Comment by hismightiness** [comment]
Actually, due to security issues, I'd suggest starting no earlier than 7.4.2.

**Comment by can-anierzad** [comment]
Does that need to be considered when using a reference that is set as `CopyLocal: False`? Or do you suggest upgrading the core version dependency to 7.4.2 as well as using the more recent NuGet packages?

**Comment by can-anierzad** [comment]
Resolved by PR #7.

**Comment by hismightiness** [comment]
I'm mostly suggesting that the extension should only support DNN 7.4.2 and newer.  I haven't looked into the project build enough yet to suggest what to do about CopyLocal.

**Comment by hismightiness** [comment]
I just pulled your updates and I built successfully.  Thanks!
