### ISSUE TITLE
Provide releases of command line client

### ISSUE THREAD

**Issue by bdukes** [cantarus/PolyDeploy#23]
Related to #22, are there plans to provide official builds of the command line client?

**Comment by can-anierzad** [comment]
@bdukes There's currently no plans as the DeployClient was intended more as an example rather than something that would be used off the shelf. However if it's proving useful we certainly could provide official builds.

@SNiels There's documentation available about the DeployClient here: https://github.com/cantarus/PolyDeploy/blob/master/docs/deploy-client.md

**Comment by can-anierzad** [comment]
Apologies, I forgot to update this but the DeployClient is now released along side PolyDeploy with each release since [v0.7.0](https://github.com/cantarus/PolyDeploy/releases/tag/v0.7.0).

Additionally #39 automated the creation of this release for ease.
